#
# Copyright 2019 Arcus Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require conf/distro/poky.conf

DISTRO = "poky-iris-ti"

IRIS_DISTRO_FEATURES_DEFAULT ?= "argp ext2 ipv4 ipv6 largefile usbhost xattr multiarch udev"

DISTRO_FEATURES = "${IRIS_DISTRO_FEATURES_DEFAULT}"

DISTRO_FEATURES:remove = "opengl"

PREFERRED_PROVIDER_jpeg = "jpeg"
PREFERRED_PROVIDER_jpeg-native = "jpeg-native"
PREFERRED_PROVIDER_make-native = "make-native"

# Prevent beaglebone-yocto machine from pulling in U-Boot build
EXTRA_IMAGEDEPENDS:remove = "virtual/bootloader"

# Use 6.6 kernel
PREFERRED_VERSION_linux-yocto = "6.6%"

# We want a squashfs rootfs
IMAGE_FSTYPES = "tar.bz2 squashfs"

# Limit to our single console port to avoid trying to start up another
SERIAL_CONSOLES = "115200;ttyS0"

# Remove bluez5 support as we do not use it
DISTRO_FEATURES_BACKFILL_CONSIDERED = "bluez5"

# Also remove rtc support which is not on this hardware
MACHINE_FEATURES_BACKFILL_CONSIDERED = "rtc"

# Make sure no kernel-image-zimage is appended, we still use uImage
IMAGE_INSTALL:remove = "kernel-image-zimage"